name: humanizer
description: Convert Dart values into human-friendly representations.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.17.0-nullsafety
  meta: ^1.3.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
